<?php
/**
 * Title: Faq Sticky
 * Slug: sticky
 * Categories: faq
 */
?>
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|xl","bottom":"var:preset|spacing|xxl"},"margin":{"top":"0","bottom":"0"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--xl);padding-bottom:var(--wp--preset--spacing--xxl)"><!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"top":"var:preset|spacing|lg","left":"var:preset|spacing|lg"}}}} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"style":{"position":{"desktop":"sticky"},"zIndex":"","top":{"desktop":"2em"},"right":{"desktop":"2em"},"bottom":{"desktop":"2em"},"left":{"desktop":"2em"}}} -->
<div class="wp-block-column"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0"}}},"layout":{"type":"flex","flexWrap":"nowrap"},"animation":{"name":"fade-in-down","duration":1}} -->
<div class="wp-block-group has-animation" style="margin-top:0;animation-name:fade-in-down;animation-duration:1s;animation-iteration-count:1"><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xxs","padding":{"top":"4px","bottom":"4px","left":"12px","right":"var:preset|spacing|xs"}},"border":{"radius":"30px","width":"1px"},"boxShadow":{"color":"var(\u002d\u002dwp\u002d\u002dpreset\u002d\u002dcolor\u002d\u002dprimary-900)"},"typography":{"fontStyle":"normal","fontWeight":"500"},"elements":{"link":{"color":{"text":"var:preset|color|primary-300"}}}},"borderColor":"primary-900","textColor":"primary-300","gradient":"light-bulb","layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"center"},"fontSize":"14","animation":{},"shadowPreset":"","shadowPresetHover":"","useCustomBoxShadow":true} -->
<div class="wp-block-group has-border-color has-primary-900-border-color has-primary-300-color has-light-bulb-gradient-background has-text-color has-background has-link-color has-14-font-size has-box-shadow" style="border-width:1px;border-radius:30px;padding-top:4px;padding-right:var(--wp--preset--spacing--xs);padding-bottom:4px;padding-left:12px;font-style:normal;font-weight:500;--wp--custom--box-shadow--color:var(--wp--preset--color--primary-900)"><!-- wp:image {"style":{"elements":{"link":{"color":{"text":"var:preset|color|primary-500"}}}},"className":"is-style-icon","textColor":"primary-500","iconSet":"phosphor-duotone","iconName":"chats-circle-duotone","iconSize":"1.5em","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 viewBox=\u00220 0 256 256\u0022 fill=\u0022currentColor\u0022\u003e\u003cpath d=\u0022M231.76,216.34a6,6,0,0,1-7.42,7.42l-29.87-8.53A72.05,72.05,0,0,1,92.06,175.89h0c1.3.07,2.61.11,3.93.11a72,72,0,0,0,67.93-95.88h0a72,72,0,0,1,59.29,106.36Z\u0022 opacity=\u00220.2\u0022/\u003e\u003cpath d=\u0022M231.79,187.33A80,80,0,0,0,169.57,72.59,80,80,0,1,0,24.21,139.33l-7.66,26.82a14,14,0,0,0,17.3,17.3l26.82-7.66a80.15,80.15,0,0,0,25.75,7.63,80,80,0,0,0,108.91,40.37l26.82,7.66a14,14,0,0,0,17.3-17.3ZM61.53,159.23a8.22,8.22,0,0,0-2.2.3l-26.41,7.55,7.55-26.41a8,8,0,0,0-.68-6,63.95,63.95,0,1,1,25.57,25.57A7.94,7.94,0,0,0,61.53,159.23Zm154,29.44,7.55,26.41-26.41-7.55a8,8,0,0,0-6,.68,64.06,64.06,0,0,1-86.32-24.64A79.93,79.93,0,0,0,174.7,89.71a64,64,0,0,1,41.51,92.93A8,8,0,0,0,215.53,188.67Z\u0022/\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image is-style-icon has-primary-500-color has-text-color has-link-color" style="--wp--custom--icon--color:var(--wp--preset--color--primary-500,currentColor);--wp--custom--icon--size:1.5em;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 256 256&quot; fill=&quot;currentColor&quot;&gt;<path d=&quot;M231.76,216.34a6,6,0,0,1-7.42,7.42l-29.87-8.53A72.05,72.05,0,0,1,92.06,175.89h0c1.3.07,2.61.11,3.93.11a72,72,0,0,0,67.93-95.88h0a72,72,0,0,1,59.29,106.36Z&quot; opacity=&quot;0.2&quot;/&gt;<path d=&quot;M231.79,187.33A80,80,0,0,0,169.57,72.59,80,80,0,1,0,24.21,139.33l-7.66,26.82a14,14,0,0,0,17.3,17.3l26.82-7.66a80.15,80.15,0,0,0,25.75,7.63,80,80,0,0,0,108.91,40.37l26.82,7.66a14,14,0,0,0,17.3-17.3ZM61.53,159.23a8.22,8.22,0,0,0-2.2.3l-26.41,7.55,7.55-26.41a8,8,0,0,0-.68-6,63.95,63.95,0,1,1,25.57,25.57A7.94,7.94,0,0,0,61.53,159.23Zm154,29.44,7.55,26.41-26.41-7.55a8,8,0,0,0-6,.68,64.06,64.06,0,0,1-86.32-24.64A79.93,79.93,0,0,0,174.7,89.71a64,64,0,0,1,41.51,92.93A8,8,0,0,0,215.53,188.67Z&quot;/&gt;</svg&gt;')"><img alt=""/></figure>
<!-- /wp:image -->
<!-- wp:paragraph -->
<p>FAQs</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
<!-- wp:heading {"gradient":"primary-background","className":"is-style-default"} -->
<h2 class="wp-block-heading is-style-default has-primary-background-gradient-background has-background">Frequently asked questions</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"style":{"elements":{"link":{"color":{"text":"var:preset|color|primary-100"}}},"maxWidth":{"all":"512px"}},"textColor":"primary-100"} -->
<p class="has-primary-100-color has-text-color has-link-color">Some of the most common questions. Can't find the right answer? Click here to contact us</p>
<!-- /wp:paragraph -->
<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"textColor":"primary-950","gradient":"primary-background","style":{"elements":{"link":{"color":{"text":"var:preset|color|primary-950"}}}},"size":"large"} -->
<div class="wp-block-button"><a class="wp-block-button__link has-primary-950-color has-primary-background-gradient-background has-text-color has-background has-link-color wp-element-button">Contact Us</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column -->
<!-- wp:column {"width":"60%","style":{"spacing":{"margin":{"top":"0","bottom":"0"}}}} -->
<div class="wp-block-column" style="margin-top:0;margin-bottom:0;flex-basis:60%"><!-- wp:group {"align":"full","style":{"elements":{"link":{"color":{"text":"var:preset|color|primary-100"}}}},"textColor":"primary-100","layout":{"type":"default"}} -->
<div class="wp-block-group alignfull has-primary-100-color has-text-color has-link-color"><!-- wp:details {"style":{"spacing":{"padding":{"top":"var:preset|spacing|sm","bottom":"var:preset|spacing|sm","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"}},"border":{"radius":"30px","width":"1px"},"position":{"desktop":"sticky"},"top":{"desktop":"2em"},"right":{"desktop":""},"bottom":{"desktop":""},"left":{"desktop":""}},"borderColor":"primary-950","backgroundColor":"neutral-900","className":"is-style-summary-heading","expandIcon":"chevron"} -->
<details class="wp-block-details is-style-summary-heading has-border-color has-primary-950-border-color has-neutral-900-background-color has-background" style="border-width:1px;border-radius:30px;padding-top:var(--wp--preset--spacing--sm);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--sm);padding-left:var(--wp--preset--spacing--sm)"><summary>How can I edit the front page?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>Editing your home page from a dedicated static front page is the recommended way to edit your home page as it ensures your changes are separate to the template and also allows SEO plugins to work correctly.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"var:preset|spacing|sm","bottom":"var:preset|spacing|sm","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"}},"border":{"radius":"30px","width":"1px"},"position":{"desktop":"sticky"},"top":{"desktop":"2em"},"right":{"desktop":""},"bottom":{"desktop":""},"left":{"desktop":""}},"borderColor":"primary-900","backgroundColor":"neutral-900","className":"is-style-summary-heading","expandIcon":"chevron"} -->
<details class="wp-block-details is-style-summary-heading has-border-color has-primary-900-border-color has-neutral-900-background-color has-background" style="border-width:1px;border-radius:30px;padding-top:var(--wp--preset--spacing--sm);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--sm);padding-left:var(--wp--preset--spacing--sm)"><summary>How to customize the theme color palette?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>This theme provides a base color palette which handles the color styles of every element and block on your site. Changing the default colors can be done in a few clicks from the Site Editor under the Styles tab.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"var:preset|spacing|sm","bottom":"var:preset|spacing|sm","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"}},"border":{"radius":"30px","width":"1px"},"position":{"desktop":"sticky"},"top":{"desktop":"2em"},"right":{"desktop":""},"bottom":{"desktop":""},"left":{"desktop":""}},"borderColor":"primary-800","backgroundColor":"neutral-900","className":"is-style-summary-heading","expandIcon":"chevron"} -->
<details class="wp-block-details is-style-summary-heading has-border-color has-primary-800-border-color has-neutral-900-background-color has-background" style="border-width:1px;border-radius:30px;padding-top:var(--wp--preset--spacing--sm);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--sm);padding-left:var(--wp--preset--spacing--sm)"><summary>How do I create a child theme?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>We recommend using the create block theme plugin to create your own child themes. With a little know-how, they can be the perfect way to build your own website. They inherit all of the parent theme's design which saves you a tonne of work and provides a head start for your next project.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"var:preset|spacing|sm","bottom":"var:preset|spacing|sm","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"}},"border":{"radius":"30px","width":"1px"},"position":{"desktop":"sticky"},"top":{"desktop":"2em"},"right":{"desktop":""},"bottom":{"desktop":""},"left":{"desktop":""}},"borderColor":"primary-700","backgroundColor":"neutral-900","className":"is-style-summary-heading","expandIcon":"chevron"} -->
<details class="wp-block-details is-style-summary-heading has-border-color has-primary-700-border-color has-neutral-900-background-color has-background" style="border-width:1px;border-radius:30px;padding-top:var(--wp--preset--spacing--sm);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--sm);padding-left:var(--wp--preset--spacing--sm)"><summary>How to keep user dark mode setting?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>Cookies can be used to store user dark mode settings when clicking the toggle switch</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"var:preset|spacing|sm","bottom":"var:preset|spacing|sm","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"}},"border":{"radius":"30px","width":"1px"},"position":{"desktop":"sticky"},"top":{"desktop":"2em"},"right":{"desktop":""},"bottom":{"desktop":""},"left":{"desktop":""}},"borderColor":"primary-600","backgroundColor":"neutral-900","className":"is-style-summary-heading","expandIcon":"chevron"} -->
<details class="wp-block-details is-style-summary-heading has-border-color has-primary-600-border-color has-neutral-900-background-color has-background" style="border-width:1px;border-radius:30px;padding-top:var(--wp--preset--spacing--sm);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--sm);padding-left:var(--wp--preset--spacing--sm)"><summary>How can I display blog posts on the home page?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>This theme comes with multiple blog patterns that can be used to display posts on any page. Simply add a blog pattern to your home page template, or the page that is set as the Front Page. You can customize the Query Loop to suit your needs.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"var:preset|spacing|sm","bottom":"var:preset|spacing|sm","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"}},"border":{"radius":"30px","width":"1px"},"position":{"desktop":"sticky"},"top":{"desktop":"2em"},"right":{"desktop":""},"bottom":{"desktop":""},"left":{"desktop":""}},"borderColor":"primary-500","backgroundColor":"neutral-900","className":"is-style-summary-heading","expandIcon":"chevron"} -->
<details class="wp-block-details is-style-summary-heading has-border-color has-primary-500-border-color has-neutral-900-background-color has-background" style="border-width:1px;border-radius:30px;padding-top:var(--wp--preset--spacing--sm);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--sm);padding-left:var(--wp--preset--spacing--sm)"><summary>How can I save user dark mode preferences?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>No, there are no plugins required by this theme. Everything you need to design an amazing website is provided by the framework.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"var:preset|spacing|sm","bottom":"var:preset|spacing|sm","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"}},"border":{"radius":"30px","width":"1px"},"position":{"desktop":"sticky"},"top":{"desktop":"2em"},"right":{"desktop":""},"bottom":{"desktop":""},"left":{"desktop":""}},"borderColor":"primary-400","backgroundColor":"neutral-900","className":"is-style-summary-heading","expandIcon":"chevron"} -->
<details class="wp-block-details is-style-summary-heading has-border-color has-primary-400-border-color has-neutral-900-background-color has-background" style="border-width:1px;border-radius:30px;padding-top:var(--wp--preset--spacing--sm);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--sm);padding-left:var(--wp--preset--spacing--sm)"><summary>How do I create an FAQ accordion?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>FAQ accordions can be created using multiple Details blocks in a column such as this one. This theme provides pre-built layouts to quickly create FAQ sections with accordion toggles.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"var:preset|spacing|sm","bottom":"var:preset|spacing|sm","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"}},"border":{"radius":"30px","width":"1px"},"position":{"desktop":"sticky"},"top":{"desktop":"2em"},"right":{"desktop":""},"bottom":{"desktop":""},"left":{"desktop":""}},"borderColor":"primary-300","backgroundColor":"neutral-900","className":"is-style-summary-heading","expandIcon":"chevron"} -->
<details class="wp-block-details is-style-summary-heading has-border-color has-primary-300-border-color has-neutral-900-background-color has-background" style="border-width:1px;border-radius:30px;padding-top:var(--wp--preset--spacing--sm);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--sm);padding-left:var(--wp--preset--spacing--sm)"><summary>What version of PHP do I need?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>PHP 7.4 or higher is required however we recommend using a later version PHP 8.2 or above.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"var:preset|spacing|sm","bottom":"var:preset|spacing|sm","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"}},"border":{"radius":"30px","width":"1px"},"position":{"desktop":"sticky"},"top":{"desktop":"2em"},"right":{"desktop":""},"bottom":{"desktop":""},"left":{"desktop":""}},"borderColor":"primary-200","backgroundColor":"neutral-900","className":"is-style-summary-heading","expandIcon":"chevron"} -->
<details class="wp-block-details is-style-summary-heading has-border-color has-primary-200-border-color has-neutral-900-background-color has-background" style="border-width:1px;border-radius:30px;padding-top:var(--wp--preset--spacing--sm);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--sm);padding-left:var(--wp--preset--spacing--sm)"><summary>How can I add animations to blocks?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>Most core blocks have animation supported added. You can add and change transition effects without needing any code.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"var:preset|spacing|sm","bottom":"var:preset|spacing|sm","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"}},"border":{"radius":"30px","width":"1px"},"position":{"desktop":"sticky"},"top":{"desktop":"2em"},"right":{"desktop":""},"bottom":{"desktop":""},"left":{"desktop":""}},"borderColor":"primary-100","backgroundColor":"neutral-900","className":"is-style-summary-heading","expandIcon":"chevron"} -->
<details class="wp-block-details is-style-summary-heading has-border-color has-primary-100-border-color has-neutral-900-background-color has-background" style="border-width:1px;border-radius:30px;padding-top:var(--wp--preset--spacing--sm);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--sm);padding-left:var(--wp--preset--spacing--sm)"><summary>Does this theme require any plugins?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>No, there are no plugins required by this theme. Everything you need to design an amazing website is provided by the framework.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"var:preset|spacing|sm","bottom":"var:preset|spacing|sm","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"}},"border":{"radius":"30px","width":"1px"},"position":{"desktop":"sticky"},"zIndex":"","top":{"desktop":"2em"},"right":{"desktop":""},"bottom":{"desktop":""},"left":{"desktop":""}},"borderColor":"primary-50","backgroundColor":"neutral-900","className":"is-style-summary-heading","expandIcon":"chevron"} -->
<details class="wp-block-details is-style-summary-heading has-border-color has-primary-50-border-color has-neutral-900-background-color has-background" style="border-width:1px;border-radius:30px;padding-top:var(--wp--preset--spacing--sm);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--sm);padding-left:var(--wp--preset--spacing--sm)"><summary>How to change the site logo?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>Head to the Site Editor and then navigate to the Header Template Part. From there, click on the existing logo and then replace it with a block of your choice. You can use an Image block, SVG, Site Logo or Site Title block as the site logo, the choice is yours. We prefer to use SVGs for logos because they scale perfectly at all screen sizes and also support variable colors which makes them ideal for use with dark mode and animations.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"style":{"spacing":{"padding":{"top":"var:preset|spacing|sm","bottom":"var:preset|spacing|sm","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"}},"border":{"radius":"30px","width":"1px"},"position":{"desktop":"sticky"},"top":{"desktop":"2em"},"right":{"desktop":""},"bottom":{"desktop":""},"left":{"desktop":""},"boxShadow":""},"borderColor":"primary-25","backgroundColor":"neutral-900","className":"is-style-summary-heading","shadowPreset":"","shadowPresetHover":"","useCustomBoxShadow":true,"expandIcon":"chevron"} -->
<details class="wp-block-details is-style-summary-heading has-border-color has-primary-25-border-color has-neutral-900-background-color has-background" style="border-width:1px;border-radius:30px;padding-top:var(--wp--preset--spacing--sm);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--sm);padding-left:var(--wp--preset--spacing--sm)"><summary>How do I add custom SVG images?</summary><!-- wp:paragraph {"placeholder":"Type / to add a hidden block"} -->
<p>Custom SVG images can be added to your site in multiple ways. The first option is to use the core Image block, however this requires the use of the Safe SVG plugin since WordPress doesn't allow SVG uploads by default. You can also use the Custom HTML WordPress block.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->